### PR TITLE
add in PATH installation

### PR DESCRIPTION
**Pull request by jasjuang**
To follow up #37 

This is for support to install latexindent in system PATH.

For Linux/MAC:

To install:
mkdir build && cd build
cmake ..
sudo make install

To uninstall:
sudo make uninstall

For Windows

To install:
right click install.bat, choose run as administrator 

To uninstall:
right click uninstall.bat, choose run as administrator 

Text editor plugins such as https://packagecontrol.io/packages/BeautifyLatex needs latexindent.pl be in PATH to work. This approach is cleaner than copying the source file to system folder manually.

### CODE REVIEW

**Comment by cmhughes** [comment]
Thanks very much for submitting this to the develop branch, and for working on the Windows bit.

I wonder about the naming of this; by calling it 'install', does that suggest that it will include the files (`latexindent` and `defaultSettings`) as part of the process? On that same note, just to clarify, are these scripts to be used once the user has already downloaded the appropriate files? As such, I wonder if your new files should be called something like, 'update path' or 'add to path' or something like that. 

What do you think? Let me know if I haven't understood this :)

**Comment by jasjuang** [comment]
There are two ways to do this, it's either make a copy of latexindent.pl and defaultsettings.yaml to location where in default PATH will point to, or append PATH with the current folder location. We try to make this process automatic.

For the linux/mac part it uses cmake to copy latexindent.pl and defaultsettings.yaml to the usr/local/bin, which is the default in PATH. This is easier than writing two seperate sh scripts to modifiy bashrc to append/remove folder location in PATH.

For the windows part using cmake is not so trivial so we settle with having two separate bat files,  install.bat simply appends the current folder location to PATH environment variable, nothing is copied, similarly uninstall.bat removes the current folder location from PATH environment variable.

**Comment by cmhughes** [comment]
Thanks for the follow-up.

So, just to clarify, let's say that I'm a user who wishes to use
latexindent.pl/.exe on a machine *without* a full TeX distribution, then I
could:

   1. download latexindent.pl (or latexindent.exe for Windows) and
   defaultSettings.yaml from here on github
   2. download the relevant installer (either CMakeLists.txt or install.bat)
   to the same directory that I have placed the files from step 1
   3. run the installer

To uninstall (remove from path), I would download the relevant file and run
it. Does this sound accurate?

Thanks again for your time on this.

Chris

**Comment by jasjuang** [comment]
Hi Chris,

Yes that is right.

Thanks,
Jason

**Comment by cmhughes** [comment]
Apologies for being slow to review this, Jason; I'm grateful for the
contribution and hope to review/test it over the next week.

**Comment by cmhughes** [comment]
I'm reviewing this and have come up against some problems, hoping you can help.

Here's what I have done:

1. I cloned your branch 
2. `mkdir build && cd build`
3. `mkdir cmake`
4. `sudo make install`

I get the following error: `make: *** No rule to make target install.  Stop.`

Can you make describe exactly what the user should do? I'm on Ubuntu Linux.

**Comment by jasjuang** [comment]
3rd step is "cmake .. ", the dot dot after is necessary. And you might need
to do "sudo apt-get install cmake" first. Let me know if you run into any
problems. Thanks.

**Comment by cmhughes** [comment]
When I run 
```
mkdir cmake ..
```
 I get:
```
mkdir: cannot create directory `..': File exists`
```
What should I do? I'm asking this mostly to clarify, but also because it's a good exercise in detailing the steps for the manual :)

**Comment by jasjuang** [comment]
It's "cmake .." , there should be no mkdir in the front. Thanks!

**Comment by cmhughes** [comment]
Thanks, that works :)

So, I can confirm that the following now work for me:
* installation on Linux
* removal on Linux
* installation on Windows
The only thing that *doesn't* work for me is *removal* on Windows. 

I test this by doing
```
echo %path%
```
which shows me my `%path%` variable, which includes the directory that I added, using `install.bat`. When I run the removal script, log off, and then `echo %path%`, the directory still persists.

Can you take another look at the Windows removal and see if you can replicate this?

**Comment by jasjuang** [comment]
Simply close the cmd window, and open a new one and it should be gone. 

If you are checking from echo %path%, it's already fixed at the moment you open it (kind of like bashrc in ubuntu), so when you modify the path you have to re-open cmd for it to work on that session.

Another thing you can check is go to control panel-> systems-> environment variables -> Path, that place updates the moment when the script is run.

 Let me know if it works for you. Thanks

**Comment by cmhughes** [comment]
You're right; my Windows `%path%` variable had a few bad entries, which messed things up. Once I removed them, the `remove-from-path.bat` worked fine.

I've merged this at https://github.com/cmhughes/latexindent.pl/commit/37c2d056d0a85d7744b83c991cb4e2f7c444be78 and you'll notice that I've renamed the Windows `.bat` files to `add-to-path.bat` and `remove-from-path.bat` respectively. My reasoning is that `install.bat` and `uninstall.bat` sound like they would contain everything the user would need (`latexindent.exe` and `defaultSettings.yaml`).

Thanks again for your contribution, I will give you credit in the documentation :) 

PS: apologies for the slow review of this, I've been struggling with some health issues.

**Comment by jasjuang** [comment]
No worries. Thanks for reviewing this thoroughly.

**Comment by jasjuang** [comment]
Hi,

I just realized that you moved the CMakeLists.txt into another folder called "path-helper-files" folder in the develop branch, that will cause sudo make install to fail because when I wrote the script I assume latexindent.pl is at the same level as CMakeLists.txt. Could you modify CMakeLists.txt accordingly?

Thanks,
Jason

**Comment by cmhughes** [comment]
Hi Jason,
Thanks for catching this, and my apologies for not checking first.

Do I just need to make the following changes?

 install(PROGRAMS ../latexindent.pl
           DESTINATION bin)

   install(FILES ../defaultSettings.yaml
           DESTINATION bin)

Let me know, and I'll make the changes, or otherwise feel free to submit a
pull request to the develop branch :)
Best
Chris

**Comment by jasjuang** [comment]
Yes that change is correct. 

Addtionally, the steps will be updated to 
mkdir build
cd build
cmake ../path-helper-files/
sudo make install

**Comment by cmhughes** [comment]
Hi Jason,
Thanks for the follow-up.

The documentation, as it stands, says
*download latexindent.pl <http://latexindent.pl>, defaultSettings.yaml, and
CMakeLists.txt from [6]to your chosen directory. *With this in mind, does
this mean that any of these changes need to be made?

I agree that they *would* need to be made if a user simply clones the
github repository and wants to run CMakeLists.txt without moving it.

What do you think?

Chris

**Comment by jasjuang** [comment]
Those parts are fine. I am referring to listing 38 at page 21 of manuel.pdf.
"cmake .." will need to be updated to "cmake ../path-helper-files/"

**Comment by cmhughes** [comment]
I've implemented your changes (and tested them); have a look at https://github.com/cmhughes/latexindent.pl/commit/304cdcd7692821a5d15e2aaeb4a906cfd93a0537 and see what you think. Thanks again for catching this, let me know if there are any other changes :)

**Comment by cmhughes** [comment]
Hi Jason,
Thanks again for your contribution.

I've implemented a brand-new approach for `latexindent.pl`; with regards to your feature, the only thing that needs updating is that for the Linux/Mac version, the directory of modules `LatexIndent/*.pm` need to be copied to the same directory as the one for `latexindent.pl`.

Do you reckon you could take care of this? Preferably with a new pull request to the develop branch. Note that you'll need to update your fork.

Let me know if you have any questions.
Many thanks
Chris

**Comment by jasjuang** [comment]
Hi Chris, please see PR #54

**Pull request merged**
