### PR TITLE
Added support for the XDG specification

### PR DESCRIPTION
**Pull request by Nehctarg**
## what is this pull request about?
The search for the config file now includes the following directories, sorted by priority:
- `$LATEXINDENT_CONFIG`
- `$XDG_CONFIG_HOME/latexindent/indentconfig.yaml`
- `$HOME/.config/latexindent/indentconfig.yaml`
- `$homeDir/indentconfig.yaml`
- `$homeDir/.indentconfig.yaml`

`$homeDir` represents the users home OS-independently, whilst `$HOME` should only be set on Linux. 

## does this relate to an existing issue?
See Issue #396.

## does this change any existing behaviour?
yes, but only marginal.

## what does this add?
Support for the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), e. g. the config file can now be placed at:
- an arbitrary place, provided this location is specified in the `LATEXINDENT_CONFIG` environment variable
- _or_ the `$XDG_CONFIG_HOME/latexindent/indentconfig.yaml`
- _or_ `$HOME/.config/latexindent/indentconfig.yaml` 
- _or_ `$homeDir/indentconfig.yaml`
- _or_ `$homeDir/.indentconfig.yaml`

`$HOME` is referencing the HOME environment variable on Linux, whilst `$homeDir` is the OS-independent home value.

## how do I test this?
Assuming bash:
```bash
export LATEXINDENT_CONFIG="path/to/your/latexindent.yaml" # this can be any path
# put some noticeable changes in your letexindent.yaml file
latexindent <some tex file> # see that latexindent uses the settings, specified in your config file located at $LATEXINDENT_CONFIG 
```

## anything else?
This change should also be recorded in the documentation, but I have no idea in which files  the config file location is mentioned.

### CODE REVIEW

**Comment by cmhughes** [comment]
Many thanks for your time on this, it looks great!

> This change should also be recorded in the documentation, but I have no idea in which files the config file location is mentioned.

Yes, could you update documentation/sec-appendices.tex perhaps as a subsection between pre-commit and log file preferences?

Another question : how does this translate to Mac and Windows?

Thanks again!

**Comment by cmhughes** [comment]
You'll also need to make sure it fails gracefully, see the test cases: https://github.com/cmhughes/latexindent.pl/actions/runs/3744063166/jobs/6358231028

**Comment by Nehctarg** [comment]
> Another question : how does this translate to Mac and Windows?


> You'll also need to make sure it fails gracefully

I implemented both of that, but the directory for mac is still wrong. That is because it is common place to store configs not in a directory named after the app (e.g. `latexindent`) but named after the reversed domain (e.g. `com.example.latexindent`). Which domain should I use, if even?

**Comment by Nehctarg** [comment]
> subsection between pre-commit and log file preferences

Should I add the subsection to pre-commit or to log file preferences?

**Comment by cmhughes** [comment]
Many thanks for your time on this!

>  I implemented both of that, but the directory for mac is still wrong. That is because it is common place to store configs not in a directory named after the app (e.g. latexindent) but named after the reversed domain (e.g. com.example.latexindent). Which domain should I use, if even?

I'm not sure, I'm not familiar with the Mac operating system. Is there guidance somewhere?

> Should I add the subsection to pre-commit or to log file preferences?

It'll be a `\section`, please, something like 
```tex
\section{indentconfig options}
```
just before the section `\section{logFilePreferences}`. Does that make sense?

**Comment by cmhughes** [comment]
It looks like line `143` is causing problems: https://github.com/cmhughes/latexindent.pl/actions/runs/3751967221/jobs/6374012379

**Comment by Nehctarg** [comment]
> Is there guidance somewhere?

This [Stackoverflow question](https://stackoverflow.com/a/5084892) because the apple developer documentation unfortunately only focuses on gui apps. But maybe I've just missed something.

**Comment by cmhughes** [comment]
Thanks for your time.

You'll see that the github check has passed, that's a good start!

failing gracefully
-
When I run the following on my Linux machine
```bash
latexindent.pl quick-start.tex
```
then I receive
```
Use of uninitialized value $ENV{"XDG_CONFIG_HOME"} in string at /home/cmhughes/projects/latexindent/LatexIndent/GetYamlSettings.pm line 125.
Use of uninitialized value $ENV{"XDG_CONFIG_HOME"} in concatenation (.) or string at /home/cmhughes/projects/latexindent/LatexIndent/GetYamlSettings.pm line 125.
```
This needs to fail gracefully. How are you testing this on your machine? 

documentation
-
Thanks for updating the documentation, you've done that in the appropriate place, great!

But, I see that the documentation details, for example
```
$XDG_CONFIG_HOME/latexindent/indentconfig.yaml
```
but when I look at `GetYamlSettings.yaml` it checks for 
```
$ENV{XDG_CONFIG_HOME}/latexindent/latexindent.yaml
```
Which is it? Also, the documentation needs details of how/why people would update this variable.

**Comment by Nehctarg** [comment]
> How are you testing this on your machine?

I'm just running `test-cases.sh -as` after adding the directory with `latexindent.pl` to my path like this: `export PATH=$PATH:$(pwd)`. Is there a better way? 

> Which is it?

This should be `latexindent.yaml`, I'm going to change that.

> Also, the documentation needs details of how/why people would update this variable

Yes, I completely missed that.

**Comment by cmhughes** [comment]
> Is there a better way?

Your method sounds good, but I'd recommend something really simple first:
```
cd documentation/demonstrations/
latexindent.pl quick-start.tex
```
This needs to accommodate _all_  possibilities:

1. users have the environment defined
2. users do _not_ have the environment variable defined
3. users don't know what an environment variable is and why they would want one
4. users have defined an environment variable with the appropriate name, but haven't done it correctly
5. and probably more :)

**Comment by Nehctarg** [comment]
This seems to work now, but I'm struggling with the `dosprompt` environment because it doesn't wrap text, any idea how to fix this?

**Comment by Nehctarg** [comment]
And I put a dead link (`https://latexindentpl.readthedocs.io/en/latest/sec-appendices.html#indentconfig-options`) in the logger output, to tell the user where the documentation for the config location places is. Will the link work, when this is merged?

**Comment by Nehctarg** [comment]
> Does this have to be this detailed? 

yes because this is in addition to `$LATEXINDENT_CONFIG`. So for example:
- the user *can* use `$LATEXINDENT_CONFIG` directly or leave it unset
- when it is unset we fallback to `$XDG_CONFIG_HOME` (which is defined by the [XDG spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) so a user might already have set it) 
- and only if this is unset either we fallback to the defalut value of the `$XDG_CONFIG_HOME` variable, which is `$HOME/.config` 


So the `$LATEXINDENT_CONFIG` and the  `$XDG_CONFIG_HOME` variables are inherently different because the XDG on is also used by other apps. 
The same thing applies to windows with their `$LOCALAPPDATA` variable, which is also shared across different apps.

**Comment by Nehctarg** [comment]
> Can you wrap it in the widepage environment, such as

I did that, and more text became visible, but the last word is still cut of.

**Comment by cmhughes** [comment]
Thanks. 

OK, so I get that `$XDG_CONFIG_HOME` is a variable that might be applicable across multiple applications, so I get why that line needs to be as it is.

But for the ` $LATEXINDENT_CONFIG` isn't that specific to latexindent....?

Don't worry about the widepage thing, I'll fix it later.

**Comment by Nehctarg** [comment]
> But for the  $LATEXINDENT_CONFIG isn't that specific to latexindent....?

Yes and it is somewhat redundant, but I allows users to specify a specific directory for their config, which might be useful and if they don't want to use this they can just leave the variable unset.

**Comment by cmhughes** [comment]
Many thanks for your time on this, I think it's shaping up nicely :) I'm grateful for your time. We're getting close to merging this.

A few minor points to address, please:

1. in your main block (Lines 132--155) in `GetYamlSettings.pm` there is a lot of duplicated checking, as it seems like almost every `if` statement checks for `!defined $indentconfig` and the logging statements check for `unless $switches{onlyDefault}`. So, can you rearrange these so that the entire block has the check `(if !defined $indentconfig and !$switches{onlyDefault})` which should allow you to remove a lot of the duplicated checks throughout the block. Does this make sense?
2. on line 125 after successful reading of `$ENV{LATEXINDENT_CONFIG}` can we have a log file message, please?
3. can you detail in the documentation what `XDG` is/stands for? If there are any relevant links/references, please feel encouraged to include them in `latex-indent.bib` (for reference: when compiling, I find it efficient to edit `latexindent.tex` so that it only `input`s the file `sec-appendices`)
4. the details you've given on how to update `$LATEXINDENT_CONFIG` are clear and helpful, and I was able to follow them. Can you add details of how to update `$XDG_CONFIG_HOME`
5. if you'd like log file 'headings' such as INFO/WARN, then begin your logfile with a '*', for example `$logger->info('*The $LATEXINDENT_CONFIG variable ...`

And, just to check my understanding, is the following an accurate summary:

- `$LATEXINDENT_CONFIG` specifies full path for a _file_
- `$XDG_CONFIG_HOME` specifies a _directory_ path
- `$LOCALAPPDATA` specifies a _directory_ path


Thanks again!

**Comment by Nehctarg** [comment]
I fixed 1, 2, 4 and thanks for 5. 
But after looking into 3 I don't think this would be worth the space it would take to full describe where this name comes from. That is mainly because the meaning of XDG (like many acronyms on Linux, see for example 'usr') changed over time, - it started as 'X Desktop Group', which is now freedesktop.org, and was then rebranded to 'Cross Desktop Group', but they still use the acronym XDG in their specs (like the basedir spec, which we are implementing) - so a full description isn't worth it in my opinion. But this is of course subjective, so your opinion would be greatly appreciated. I could also just link to [Wikipedia's XDG article](https://en.wikipedia.org/wiki/XDG), a [Superuser question](https://superuser.com/a/1559358) or directly to the specification section of the [freedesktop.org wiki](https://www.freedesktop.org/wiki/) , which would describe it for me. 
> And, just to check my understanding, is the following an accurate summary:

Yes, this is fully correct. The only thing to add might be, that `$XDG_CONFIG_HOME` is Unix specific, whilst `$LOCALAPPDATA` is a windows thing.

**Comment by cmhughes** [comment]
That's great, thanks very much!

I've merged this into `develop`, and it'll be part of the next release, hopefully coming early in 2023. 

Thanks again!

**Comment by cmhughes** [comment]
I had to update `GetYamlSettings.pm` at https://github.com/cmhughes/latexindent.pl/commit/8e3ec0917d7435bf8bcceaf3f14c91b2bcdee3ea to make sure that `.indentconfig.yaml` is only read if `indentconfig.yaml` has not been read. 

This was part of the original `GetYamlSettings.yaml`, which you deleted; it's great to make changes, and I'm grateful, but please do be careful. Obviously, it's ultimately my responsibility to catch this kind of thing :)

**Pull request merged**
