### PR TITLE
defaultSettings and schema

### PR DESCRIPTION
**Pull request by arkandias**
The file defaultSettings.yaml was an invalid YAML because of unexpected alias/scalars. This is easily fixed by adding single quotes (double in one case).
Also, the indentation was inconsistent (sometimes 4, 2 or 3 spaces), so I just used Prettier to format it (actually I had to realign the comments afterwards).
Finally I completed latexindent-yaml-schema.json file with several missing fields.

### CODE REVIEW

**Comment by cmhughes** [comment]
Thanks for this.

The indentation changes look fine.

I'm not sure why the quotes are needed....?

**Comment by arkandias** [comment]
Hi, I am no expert in YAML. The formatter (Prettier in my case -- but I also tried with Red Hat's YAML plugin in VS Code) throw the following errors when trying to save the file defaultSettings.yaml (I also tried a YAML validator online, which returned exactly the same errors).

The following field yields an "Unexpected alias at node end"
```
specialBeginEnd:
  inlineMath:
    body: [^$]*?
```
while the four ones below yield an "Unexpected scalar at node end"
```
fineTuning:
    environments:
      name: [a-zA-Z@\*0-9_\\]+
    commands:
      name: [+a-zA-Z@\*0-9_\:]+?
    keyEqualsValuesBracesBrackets:
      name: [a-zA-Z@\*0-9_\/.:\#-]+[a-zA-Z@\*0-9_\/.\h\{\}:\#-]*?
    namedGroupingBracesBrackets:
      name: [0-9\.a-zA-Z@\*><]+?
```
The first one can be escaped with double quotes, but the others need single quotes (because of the escaped characters `\*`, `\\`, etc.).

By the way, fields like
```
replacements:
  -
    amalgamate: 1
  -
    this: latexindent.pl
    that: pl.latexindent
    lookForThis: 0
    when: before
```
can be rewritten
```
replacements:
  - amalgamate: 1
  - this: latexindent.pl
    that: pl.latexindent
    lookForThis: 0
    when: before
```
(actually this is handled by any formatter I tried).

**Comment by cmhughes** [comment]
OK, many thanks.

In which case, can you remove the extra quotes from defaultSettings and
keep it only to formatting changes?

**Comment by arkandias** [comment]
Done!

**Comment by cmhughes** [comment]
Great, thanks so much!

**Pull request merged**
