### PR TITLE
readme: updating getting started, include option to use conda

### PR DESCRIPTION
**Pull request by tdegeus**

### CODE REVIEW

**Comment by cmhughes** [comment]
Thanks for this.

I'm happy to have *additions* to the README, but I don't want too many structural changes.

Can you change this so that you have only *added* a new section for the conda stuff? Can you also make it so that it links to the conda home page?

Thanks very much!

**Comment by tdegeus** [comment]
I can do that, though I do think it is worth to consider these changes: I had difficulties getting an overview from the readme, partly because the structure confused me (although that could be personal) and partly because there is a duplicate concerning `latexindent.exe`.

**Comment by tdegeus** [comment]
In addition, I did fix some typos as well

**Comment by cmhughes** [comment]
OK, many thanks, that's helpful.

Given that yours is the only feedback I've had on the README, I'm happy to accept this as is.

Thanks, and sorry for the noise.

**Pull request merged**
