### PR TITLE
Search localSettings in CWD as well

### PR DESCRIPTION
**Pull request by jeanlego**
This commit adds the ability to also search for localSettings.yaml in CWD if it was not found in the path of the working file.

### CODE REVIEW

**Comment by cmhughes** [comment]
Many thanks. I'll take a look and report back. First glance looks good.

**Comment by cmhughes** [comment]
Thanks very much for this, it works great. 

I reset the appveyor and travis files, as this feature doesn't need testing there. 

Thanks for the updates to the documentation, too, that's all great. It'll be part of the next release -- not sure when that will be.

Thanks again :)

**Comment by cmhughes** [comment]
This has been merged in https://github.com/cmhughes/latexindent.pl/commit/b72c0ee9d73ead5a33f25f0ccbcc29e09c2a33cb I'm not sure why github hasn't updated with the information. 

If I've missed something let me know.

**Comment by jeanlego** [comment]
> If I've missed something let me know

No that looks good to me :) 
Thanks you!

**Comment by jeanlego** [comment]
I can spend a moment to get that working for every file passed in for -l too if there's any use for that, I feel it would be more homogeneous throughout if it did it for all values passed in to -l rather than just the empty one if that makes sense?

**Comment by cmhughes** [comment]
Oh, yes, that makes sense. I should have thought of this, thanks for taking
it on.

**Pull request closed without merging**
