### PR TITLE
add in make install/uninstall support

### PR DESCRIPTION
**Pull request by jasjuang**
This is for support to install latexindent in system PATH. 

To install:
    mkdir build && cd build
    mkdir cmake ..
    sudo make install

To uninstall:
    sudo make uninstall

Text editor plugins such as https://packagecontrol.io/packages/BeautifyLatex needs latexindent.pl be in PATH to work. This approach is cleaner than copying the source file to system folder manually.

### CODE REVIEW

**Comment by cmhughes** [comment]
Hi Jasjuang,
Thanks very much for your contribution, this looks interesting! Can I clarify a couple of things :) 

- Is this mainly for a particular operating system? Presumably for Linux and/or Mac, and not for Windows.
- Is this designed for users who don't use a 'mainstream' TeX distribution? `latexindent.pl` ships with both MiKTeX and TeXLive, and I thought that they handled the path operations as part of the install...

Let me know!
Best
Chris

**Comment by jasjuang** [comment]
1. One of the main sell point of CMake is it's cross platform so it also works with windows.

2. I think yes. I am using overleaf mainly because of the semi-live compilation and the ease of collaboration with other people which MiKTeX and TeXLive lack of, but unfortunately overleaf has not integrate latexindent.pl yet. If I get a poorly formatted tex file from my colleague and can simply open in a general text editor (for example, sublime) and autoformat and put back to overleaf without having to install MiKTeX and TeXLive that will be super awesome.

**Comment by cmhughes** [comment]
Hi Jason,
Thanks for the details. I like the sound of this feature, and I think that it would work well.

Could you do a couple of things:
- include an update to the documentation detailing how users can use this feature for Windows, Linux and Mac (would your instructions above work on Windows, for example? I've never been able to get the DOS prompt to use `&&`.). In particular, I think that such detailed instructions would go nicely in a new Appendix at the end, with a sentence that points to it in Section 3.
- re-submit this pull request to the `develop` branch (when a new release is ready, I merge `develop` into `master`)

Thanks again.
Best
Chris

**Comment by jasjuang** [comment]
Hi Chris,

I need some help on getting it even to run normally on windows so I can add in the instructions. 

When I try perl latexindent.pl test.tex, I get the following error,

Can't locate YAML/Tiny.pm in @INC (@INC contains: /usr/lib/perl5/5.8.8/msys /usr
/lib/perl5/5.8.8 /usr/lib/perl5/site_perl/5.8.8/msys /usr/lib/perl5/site_perl/5.
8.8 /usr/lib/perl5/site_perl .) at latexindent.pl line 39.
BEGIN failed--compilation aborted at latexindent.pl line 39.

So I tried perl -MCPAN -e 'install "YAML::Tiny"' and perl -MCPAN -e 'install "File::HomeDir"' both in admin mode and neither of them worked and the last few line returns 

    -- NOT OK
Running make test
  Can't test without successful make
Running make install
  make had returned bad status, install seems impossible

Please let me know.

Thanks,
Jason

**Comment by cmhughes** [comment]
Thanks for the follow-up; I agree that it would be nice to have the perl
version run on Windows, although I've had a fair bit of difficulty doing so
in the past.

Can you get the .exe version to work instead?

**Comment by jasjuang** [comment]
In order to make it work on windows, one has to have visual studio installed and cmake with the install path specified, open visual studio to run it. With that many steps IMO defeats the purpose of simplifying the process. I would rather have a install.bat and uninstall.bat for windows, so the process of getting it in PATH is only double clicking a bat file once. 

Would you still accept the pull request if this is a linux/mac feature?

**Comment by cmhughes** [comment]
I think the idea of having a separate installer for Windows is fine; I'd
like to see it named as a .exe file which has screens that allow the user
to choose where to put latexindent.exe and defaultSettings.yaml. Does that
make sense?

**Pull request closed without merging**
