### PR TITLE
Clickable link doesn't need to be duplicated

### PR DESCRIPTION
**Pull request by douglasrizzo**

### CODE REVIEW

**Comment by cmhughes** [comment]
Hello!
Thanks for this. Doesn't this make the link so that it isn't clickable? That doesn't seem desirable. Have I misunderstood?
Chris

**Comment by douglasrizzo** [comment]
I tested it in [my own fork](https://github.com/douglasrizzo/latexindent.pl/tree/patch-1) and it worked just fine when displayed on GitHub. I guess I can do a better job and try to describe where the links point to instead of just showing the link in the Readme...

**Comment by douglasrizzo** [comment]
Just to clarify, on GitHub the link is clickable if you paste it raw, like http://www.google.com, so I didn't see the need to do something like `[http://www.google.com](http://www.google.com)`. I've added two more commits hiding the raw links into more reader-friendly versions and organizing the title levels of the readme. I start to feel like this is more of a cosmetic change, so if you don't want to accept it, I can understand it.

**Comment by cmhughes** [comment]
Thanks for the follow-up, that makes sense. 

You've now made quite a few changes to `readme.md`. I think that I understand why you would make these changes, as they would fit your personal preferences and style. 

I think it's important for me to say that `readme.md` is, along with the documentation, quite personal to *me*. It is my way of broadcasting and communicating the project to the user community. 

I happily consider feature requests, and do my best to implement them. But when it comes to communicating with the community, I'd prefer to keep that personal to me. As such, I'll be rejecting this pull request, but do feel free to submit others for review in the future. 

Thanks again for your interest in `latexindent.pl`, 
All the best,
Chris

**Pull request closed without merging**
