### PR TITLE
Create cruft directory if it does not exist

### PR DESCRIPTION
**Pull request by jessestricker**
what is this pull request about?
-
This creates the cruft directory if it does not already exist.

does this relate to an existing issue?
-
fixes: #452

how do I test this?
-
1. make sure the cruft directory does not exist.
2. run latexindent with `--cruft=...`
3. it should not raise an error and exit but create the directory and continue

anything else?
-
I've never written a line of Perl before, so please give feedback.

Also, is there any other place where the directory might be accessed and thus need to be created?
What about these places:
- https://github.com/cmhughes/latexindent.pl/blob/c702424c2c8152fe6fc33df6a1e9a54b55c36b88/LatexIndent/Document.pm#L274
- https://github.com/cmhughes/latexindent.pl/blob/c702424c2c8152fe6fc33df6a1e9a54b55c36b88/LatexIndent/BackUpFileProcedure.pm#L151

### CODE REVIEW

**Comment by cmhughes** [comment]
Thanks for this, it looks good!

Hopefully there's only one place where the directory existence needs checking.

I'll take a closer look soon. Thanks again for taking this on!

**Comment by cmhughes** [comment]
I think we still need an existence check on the cruft directory, so

```perl
        if ( !( -d ${$self}{cruftDirectory} ) ) {
             make_path( ${$self}{cruftDirectory} );
             if ( !( -d ${$self}{cruftDirectory} ) ) {
                  $logger->fatal( "*Could not find directory " . decode( "utf-8", ${$self}{cruftDirectory} ) );
                  $logger->fatal("Exiting, no indentation done.");
                  $self->output_logfile();
                 exit(6);
           }
     }
```
does that make sense? 

Please can you also 
* update `documentation/sec-how-to-use.tex` under the cruft directory part to detail that `latexindent.pl` will attempt to create the directory if it doesn't exist?
* update `documentation/sec-appendices.tex` with the new dependency (`use File::Path`)

**Comment by cmhughes** [comment]
Any luck with this?

**Comment by jessestricker** [comment]
I needed to read up on how Perl actually works, sorry for the delay.

**Comment by jessestricker** [comment]
I think it's ready for review. Do the documentation changes suffice? If anything sounds weird, English isn't my native language, feel free to fix as needed.

**Comment by cmhughes** [comment]
Many thanks, this is great, I'll get it released soon :) thanks so much for your contribution!

**Comment by jessestricker** [comment]
Do you happen to know when this will be available on MikTeX?

**Comment by cmhughes** [comment]
I want to try resolving a few of the open issues and then I'll get a
release. Should be within a week or so

**Comment by cmhughes** [comment]
Released today

**Pull request merged**
