### PR TITLE
V3.5.3

### PR DESCRIPTION
**Pull request by cmhughes**
A minor release that addresses the `indentconfig.yaml/.indentconfig.yaml` bug reported at https://github.com/cmhughes/latexindent.pl/issues/141

### CODE REVIEW

**Comment by lucbouge** [comment]
Thanks, Chris. Congrats for your reactivity.

I installed latexindent on my Mac with HomeBrew. Will you new version be pushed there at some point?

Luc.

**Comment by lucbouge** [comment]
Sorry, I made a mistake. Latexindent was installed through MacTeX Tex Live Utility. 
Currently, the version shipped there is 
```
cat-version: 3.5.2
cat-date:    2018-10-06 19:47:32 +0200
```
Will you eventually update MacTex with this new version?

Luc.

**Comment by cmhughes** [comment]
I uploaded it to ctan today. It should be available through your
distribution in the next few days. :)

**Comment by cmhughes** [comment]
Hi Luc,
I had confirmation from ctan that this version is now on ctan. If you update your distribution, I'd hope that it will update latexindent.

Best
Chris

**Comment by lucbouge** [comment]
Perfect. I did it without problem. Thanks for your reactivity. Luc.

**Pull request merged**
